name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ 8.3, 8.2, 8.1 ]
        laravel: [ "^11.0", "^10.0" ]
        include_security: [true, false]  # Adding conditional package inclusion
        include:
          - laravel: "^11.0"
            testbench: 9.*
          - laravel: "^10.0"
            testbench: 8.*
        exclude:
          - laravel: "^11.0"
            php: 8.1
          - laravel: "^11.0"
    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${ matrix.include_security && 'With Security' || 'Without Security' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: curl, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, iconv
          coverage: none
      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}"
          if ${{ matrix.include_security }}
          then
            composer require "graham-campbell/security-core:^4.0"
          else
            composer remove graham-campbell/security-core --no-update
          fi
          composer update
      - name: Execute tests
        run: vendor/bin/phpunit ./tests